version: '3.8'

services:
  app:
    build:
      context: .
    image: shrtly-backend-api
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
        SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
        DB_CONNECTION: ${DB_CONNECTION}
        DB_USERNAME: ${DB_USERNAME}
        DB_PASSWORD: ${DB_PASSWORD}
        JWT_SECRET: ${JWT_SECRET}
        TOKEN_EXPIRATION: ${TOKEN_EXPIRATION}

    networks:
      - app-network


  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 3
    ports:
      - "3306:3306"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
